[[puzzles]]
name = "Day 1: Trebuchet"
link = "https://adventofcode.com/2023/day/1"
[[puzzles.examples]]
args = ["""1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet"""]
result = 142
[[puzzles]]
name = "Day 1: Historian Hysteria"
link = "https://adventofcode.com/2024/day/1"
[[puzzles.examples]]
args = ["""3   4
4   3
2   5
1   3
3   9
3   3"""]
result = 11
[[puzzles]]
name = "Day 1 Part 2: Historian Hysteria"
link = "https://adventofcode.com/2024/day/1"
[[puzzles.examples]]
args = ["""3   4
4   3
2   5
1   3
3   9
3   3"""]
result = 31
[[puzzles]]
name = "Day 5: Print Queue"
link = "https://adventofcode.com/2024/day/5"
[[puzzles.examples]]
args = ["""47|53
97|13
97|61
97|47
75|29
61|13
75|53
29|13
97|29
53|29
61|53
97|53
61|29
47|13
75|47
97|75
47|61
75|61
47|29
75|13
53|13

75,47,61,53,29
97,61,53,29,13
75,29,13
75,97,47,61,53
61,13,29
97,13,75,29,47"""]
result = 143