[[puzzles]]
name = "Day 1: Trebuchet"
link = "https://adventofcode.com/2023/day/1"
[[puzzles.examples]]
args = ["""1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet"""]
result = 142
[[puzzles]]
name = "Day 1: Historian Hysteria"
link = "https://adventofcode.com/2024/day/1"
[[puzzles.examples]]
args = ["""3   4
4   3
2   5
1   3
3   9
3   3"""]
result = 11
